#!/usr/bin/env php
<?php
define('LARAVEL_START', microtime(true));
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$status = $app->make(Illuminate\Contracts\Console\Kernel::class)->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);
$app->make(Illuminate\Contracts\Console\Kernel::class)->terminate($input, $status);
exit($status);