<?php
return [
 'default'=>env('DB_CONNECTION','mysql'),
 'connections'=>[
  'mysql'=>[
   'driver'=>'mysql','url'=>env('DATABASE_URL'),'host'=>env('DB_HOST','127.0.0.1'),
   'port'=>env('DB_PORT','3306'),'database'=>env('DB_DATABASE','satu_data'),
   'username'=>env('DB_USERNAME','root'),'password'=>env('DB_PASSWORD',''),
   'unix_socket'=>env('DB_SOCKET',''),'charset'=>'utf8mb4','collation'=>'utf8mb4_unicode_ci',
   'prefix'=>'','prefix_indexes'=>true,'strict'=>true,'engine'=>null,
  ],
  'sqlite'=>['driver'=>'sqlite','url'=>env('DATABASE_URL'),'database'=>env('DB_DATABASE',database_path('database.sqlite')),'prefix'=>'','foreign_key_constraints'=>true],
 ],
 'migrations'=>'migrations',
 'redis'=>[
  'client'=>env('REDIS_CLIENT','phpredis'),
  'default'=>['host'=>env('REDIS_HOST','127.0.0.1'),'password'=>env('REDIS_PASSWORD',null),'port'=>env('REDIS_PORT',6379),'database'=>env('REDIS_DB','0')],
 ],
];