<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $title ?? 'Admin' }} - Satu Data</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
<style>body{background:#f1f5f9}.sidebar{width:250px;min-height:100vh;background:#0f172a;color:#cbd5e1;position:fixed}.sidebar a{color:#cbd5e1;text-decoration:none;display:block;padding:11px 16px;border-radius:10px}.sidebar a:hover,.sidebar a.active{background:#1e3a8a;color:#fff}.main{margin-left:250px}.topbar{background:#fff;border-bottom:1px solid #e5e7eb}.stat{border:0;border-radius:18px}.icon-box{width:48px;height:48px;border-radius:14px;background:#eff6ff;color:#2563eb;display:flex;align-items:center;justify-content:center;font-size:22px}@media(max-width:800px){.sidebar{width:70px}.sidebar .label,.sidebar .brand-label{display:none}.main{margin-left:70px}}</style></head>
<body><aside class="sidebar p-3"><div class="fw-bold text-white fs-5 mb-4"><i class="bi bi-database-fill me-2"></i><span class="brand-label">Satu Data</span></div>
<a href="{{ route('admin.dashboard') }}"><i class="bi bi-speedometer2 me-2"></i><span class="label">Dashboard</span></a>
<a href="{{ route('admin.datasets.index') }}"><i class="bi bi-files me-2"></i><span class="label">Dataset</span></a>
<a href="{{ route('admin.categories.index') }}"><i class="bi bi-tags me-2"></i><span class="label">Kategori</span></a>
<a href="{{ route('admin.organizations.index') }}"><i class="bi bi-building me-2"></i><span class="label">Instansi</span></a>
<hr><a href="{{ route('home') }}" target="_blank"><i class="bi bi-globe2 me-2"></i><span class="label">Lihat Portal</span></a>
<form method="post" action="{{ route('admin.logout') }}">@csrf<button class="btn btn-link text-start text-danger w-100 px-3"><i class="bi bi-box-arrow-right me-2"></i><span class="label">Keluar</span></button></form>
</aside><main class="main"><div class="topbar px-4 py-3 d-flex justify-content-between"><div><h5 class="mb-0 fw-bold">@yield('page-title','Dashboard')</h5></div><div class="small text-muted"><i class="bi bi-person-circle me-1"></i>{{ session('admin_name') }}</div></div><div class="p-4">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $e)<li>{{ $e }}</li>@endforeach</ul></div>@endif @yield('content')</div></main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>@stack('scripts')</body></html>